import { expect, test } from 'bun:test';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkComments, checkDocCap, checkFragments } from '../../tools/lint-prose-extras.js';

function fixture(name: string, body: string): string {
    const dir = mkdtempSync(join(tmpdir(), 'prose-'));
    const path = join(dir, name);
    writeFileSync(path, body);
    return path;
}

test('a file at the cap passes', () => {
    const path = fixture('ok.md', 'line\n'.repeat(150));
    expect(checkDocCap([path])).toEqual([]);
});

test('a file over the cap is reported once', () => {
    const path = fixture('big.md', 'line\n'.repeat(151));
    const found = checkDocCap([path]);
    expect(found.length).toBe(1);
    expect(found[0].check).toBe('doc-cap');
    expect(found[0].message).toContain('151');
});

test('a generated file is exempt', () => {
    const path = fixture('gen.md', `<!-- GENERATED by tools/x.ts -->\n${'line\n'.repeat(900)}`);
    expect(checkDocCap([path])).toEqual([]);
});

test('a short paragraph is a fragment', () => {
    const path = fixture('frag.md', 'A full sentence with enough words to pass.\n\nNot anymore.\n');
    const found = checkFragments([path]);
    expect(found.length).toBe(1);
    expect(found[0].check).toBe('fragment');
    expect(found[0].line).toBe(3);
});

test('headings, list items, table rows and code are not fragments', () => {
    const body = ['# Title', '', '- one', '', '* two', '', '> three', '', '1. four', '', '| a |', '', '<!-- note -->', '', '```', 'code()', '```', ''].join('\n');
    expect(checkFragments([fixture('skip.md', body)])).toEqual([]);
});

test('a breadcrumb is navigation, but a short paragraph beside it is still a fragment', () => {
    const body = '[Manual](README.md) › Scripting API\n\n# Scripting API\n\nNot anymore.\n';
    const found = checkFragments([fixture('crumb.md', body)]);
    expect(found.map(f => f.line)).toEqual([5]);
    expect(found[0].message).toContain('Not anymore.');
});

test('a long paragraph passes', () => {
    const path = fixture('long.md', 'This paragraph carries more than four words.\n');
    expect(checkFragments([path])).toEqual([]);
});

test('a multi-line paragraph is not a fragment', () => {
    const path = fixture('multi.md', 'Short line one\nshort line two\n');
    expect(checkFragments([path])).toEqual([]);
});

test('a rationale comment without a Why: tag is reported', () => {
    const path = fixture('why.ts', '// The cache is skipped because the lock is held.\nexport const a = 1;\n');
    const found = checkComments([path]);
    expect(found.some(f => f.check === 'why-tag')).toBe(true);
});

test('a rationale comment carrying a Why: tag passes', () => {
    const path = fixture('tagged.ts', '// Why: the cache is skipped because the lock is held.\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'why-tag')).toEqual([]);
});

test('a comment block over two lines is reported', () => {
    const path = fixture('block.ts', '// one\n// two\n// three\nexport const a = 1;\n');
    const found = checkComments([path]);
    expect(found.some(f => f.check === 'comment-block')).toBe(true);
});

test('a two-line comment block passes', () => {
    const path = fixture('short.ts', '// one\n// two\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a JSDoc block with two payload lines passes', () => {
    const path = fixture('jsdoc.ts', '/**\n * one\n * two\n */\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a JSDoc block with three payload lines is reported', () => {
    const path = fixture('jsdoc-long.ts', '/**\n * one\n * two\n * three\n */\nexport const a = 1;\n');
    const found = checkComments([path]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('3-line');
});

test('a usage block of runnable commands is not a comment block', () => {
    const body = ['// Usage:', '//   bun tools/coaltrucks-test.ts --phase cross --speed 300 --minutes 3   # proves the log balance level', '//   bun tools/coaltrucks-test.ts --minutes 45                            # full uncheated loop', '//   ENGINE_DIR=... sh tools/deploy-local.sh   # once', 'export const a = 1;', ''].join('\n');
    expect(checkComments([fixture('usage.ts', body)])).toEqual([]);
});

test('a rationale block of the same length is still a comment block', () => {
    const body = ['// The cache is skipped while the lock is held.', '// Callers then re-read the manifest.', '// A stale entry would otherwise survive the swap.', 'export const a = 1;', ''].join('\n');
    const found = checkComments([fixture('rationale.ts', body)]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('3-line');
});

test('a lint directive is never reported', () => {
    const path = fixture('directive.ts', '// eslint-disable-next-line no-restricted-imports -- the adapter is not ready\n// @ts-expect-error upstream types are wrong because the overload is missing\n// prettier-ignore\nexport const a = 1;\n');
    expect(checkComments([path])).toEqual([]);
});
