import { expect, test } from 'bun:test';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkDocCap } from '../../tools/lint-prose-extras.js';

function fixture(name: string, body: string): string {
    const dir = mkdtempSync(join(tmpdir(), 'prose-'));
    const path = join(dir, name);
    writeFileSync(path, body);
    return path;
}

test('a file at the cap passes', () => {
    const path = fixture('ok.md', 'line\n'.repeat(150));
    expect(checkDocCap([path])).toEqual([]);
});

test('a file over the cap is reported once', () => {
    const path = fixture('big.md', 'line\n'.repeat(151));
    const found = checkDocCap([path]);
    expect(found.length).toBe(1);
    expect(found[0].check).toBe('doc-cap');
    expect(found[0].message).toContain('151');
});

test('a generated file is exempt', () => {
    const path = fixture('gen.md', `<!-- GENERATED by tools/x.ts -->\n${'line\n'.repeat(900)}`);
    expect(checkDocCap([path])).toEqual([]);
});
